services:
  postgres:
    image: postgres:17.2
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    command:
      - -c
      - listen_addresses=*
      - -c
      - wal_level=logical
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  electric:
    image: electricsql/electric:1.1.1
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/postgres?sslmode=disable"
      ELECTRIC_INSECURE: true
    ports:
      - "127.0.0.1:5433:3000"
    depends_on:
      postgres:
        condition: service_healthy
